### ISSUE TITLE
heartbeat to detect disconnects

### ISSUE THREAD

**Issue by oreoshake** [jordansissel/syslog-shipper#5]
And potentially reconnect automatically after network disruptions?

**Comment by jordansissel** [comment]
If I'm saying things you already know, I apologize ;)

Syslog doesn't support heartbeats. It's also not a bidirectional protocol, it's one-way. The hacks that enable syslog over TCP and SSL/TLS don't add any message loss protection across tcp-level failures since the kernel handles payload acknowledgement, not the application.

Even using TCP keepalive or some other keep alive technique, you still have an known amount of data lost across the failure again due to the lack of message acknowledgement. The rsyslog author wrote a protocol (RELP) to try and resolve this, but I've never seen it in the wild. It's likely a more well-supported messaging protocol would be useful, here, like AMQP, STOMP, XMPP, or IRC.

 To the best of my knowledge, you can't implement an application-level message acknowledgement over a protocol that is simply a one-way stream of data. Realistically speaking, if you care about your data, you don't use syslog at all.

All of that said, I am open to proposals :)

**Comment by oreoshake** [comment]
Yeah you're right. Besides, my use case was when I switched interfaces. It didn't rebind and all messages were lost.
